echo ; Comment lines start with a semi-colon. > "C:\SQLLIB\db2cli.ini"
echo ;>> "C:\SQLLIB\db2cli.ini"
echo [tstcli1x]>> "C:\SQLLIB\db2cli.ini"
echo uid=userid>> "C:\SQLLIB\db2cli.ini"
echo pwd=password>> "C:\SQLLIB\db2cli.ini"
echo autocommit=0>> "C:\SQLLIB\db2cli.ini"
echo TableType="'TABLE','VIEW','SYSTEM TABLE'">> "C:\SQLLIB\db2cli.ini"
echo ;>> "C:\SQLLIB\db2cli.ini"
echo [tstcli2x]>> "C:\SQLLIB\db2cli.ini"
echo ;Assuming dbalias2 is a database in DB2 for MVS.>> "C:\SQLLIB\db2cli.ini"
echo SchemaList="'OWNER1','OWNER2',CURRENT SQLID">> "C:\SQLLIB\db2cli.ini"
echo ;>> "C:\SQLLIB\db2cli.ini"
echo [MyVeryLongDBALIASName]>> "C:\SQLLIB\db2cli.ini"
echo dbalias=dbalias3>> "C:\SQLLIB\db2cli.ini"
echo SysSchema=MYSCHEMA>> "C:\SQLLIB\db2cli.ini"
echo ;>> "C:\SQLLIB\db2cli.ini"
echo [HISERIES]>> "C:\SQLLIB\db2cli.ini"
echo BRANCH>> "C:\SQLLIB\db2cli.ini"
echo ;DBALIAS=HISERIES>> "C:\SQLLIB\db2cli.ini"
echo ;DBALIAS=HISERIE2>> "C:\SQLLIB\db2cli.ini"
echo OK!!
pause 
